CREATE TABLE goal_signal (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      VARCHAR(255) NOT NULL,
    tenancy_id    VARCHAR(255) NOT NULL,
    goal_name     VARCHAR(200) NOT NULL,
    success_count INT          NOT NULL DEFAULT 0,
    failure_count INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_goal_signal UNIQUE (agent_id, tenancy_id, goal_name)
);
