CREATE TABLE agent_descriptor (
    internal_id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_id               VARCHAR(255)    NOT NULL,
    tenancy_id             VARCHAR(255)    NOT NULL,
    name                   VARCHAR(255),
    version                VARCHAR(255),
    provider               VARCHAR(255),
    model_family           VARCHAR(255),
    model_version          VARCHAR(255),
    weights_fingerprint    VARCHAR(255),
    domain_vocabulary      TEXT,
    slot_vocabulary        TEXT,
    disposition_vocabulary TEXT,
    style_vocabulary       TEXT,
    axis_vocabularies      TEXT,
    slot                   VARCHAR(255),
    jurisdiction           TEXT,
    data_handling_policy   TEXT,
    briefing               TEXT,
    disposition            TEXT,
    templates              TEXT,
    CONSTRAINT uq_agent UNIQUE (agent_id, tenancy_id)
);
CREATE INDEX idx_agent_descriptor_tenancy_slot ON agent_descriptor(tenancy_id, slot);

CREATE TABLE agent_capability (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descriptor_id       BIGINT        NOT NULL
                            REFERENCES agent_descriptor(internal_id) ON DELETE CASCADE,
    agent_id            VARCHAR(255)  NOT NULL,
    tenancy_id          VARCHAR(255)  NOT NULL,
    name                VARCHAR(255)  NOT NULL,
    description         TEXT,
    capability_vocabulary TEXT,
    quality_hint        DOUBLE PRECISION,
    latency_hint_p50_ms BIGINT,
    cost_hint           VARCHAR(255),
    input_types         TEXT,
    output_types        TEXT,
    tags                TEXT,
    epistemic_domains   TEXT,
    UNIQUE (descriptor_id, name)
);
CREATE INDEX idx_agent_capability_name ON agent_capability(name);

CREATE TABLE agent_capability_excluded_domain (
    capability_id BIGINT       NOT NULL
                      REFERENCES agent_capability(id) ON DELETE CASCADE,
    domain        VARCHAR(200) NOT NULL,
    PRIMARY KEY (capability_id, domain)
);

CREATE TABLE agent_state (
    agent_id     VARCHAR(255)             NOT NULL,
    tenancy_id   VARCHAR(255)             NOT NULL,
    degradation  VARCHAR(50)              NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (agent_id, tenancy_id)
);

CREATE TABLE capability_specialization (
    agent_id        VARCHAR(255) NOT NULL,
    tenancy_id      VARCHAR(255) NOT NULL,
    capability_name VARCHAR(100) NOT NULL,
    domain          VARCHAR(200) NOT NULL,
    decline_count   INT          NOT NULL DEFAULT 0,
    last_declined   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (agent_id, tenancy_id, capability_name, domain)
);

CREATE TABLE behavioral_signal (
    agent_id        VARCHAR(255) NOT NULL,
    tenancy_id      VARCHAR(255) NOT NULL,
    capability_name VARCHAR(100) NOT NULL,
    qualifier       VARCHAR(200) NOT NULL,
    signal_type     VARCHAR(20)  NOT NULL,
    signal_count    INT          NOT NULL DEFAULT 0,
    last_recorded   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (agent_id, tenancy_id, capability_name, qualifier, signal_type)
);

CREATE TABLE agent_goal (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descriptor_id  BIGINT       NOT NULL REFERENCES agent_descriptor(internal_id) ON DELETE CASCADE,
    agent_id       VARCHAR(255) NOT NULL,
    tenancy_id     VARCHAR(255) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT         NOT NULL,
    priority       VARCHAR(20)  NOT NULL,
    visibility     VARCHAR(20)  NOT NULL,
    capabilities   TEXT,
    UNIQUE (descriptor_id, name)
);

CREATE TABLE agent_constraint (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descriptor_id  BIGINT       NOT NULL REFERENCES agent_descriptor(internal_id) ON DELETE CASCADE,
    agent_id       VARCHAR(255) NOT NULL,
    tenancy_id     VARCHAR(255) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT         NOT NULL,
    visibility     VARCHAR(20)  NOT NULL,
    severity       VARCHAR(20)  NOT NULL,
    UNIQUE (descriptor_id, name)
);

CREATE TABLE disposition_signal (
    agent_id        VARCHAR(255) NOT NULL,
    tenancy_id      VARCHAR(255) NOT NULL,
    function_term   VARCHAR(30)  NOT NULL,
    count           INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (agent_id, tenancy_id, function_term)
);

CREATE TABLE goal_signal (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      VARCHAR(255) NOT NULL,
    tenancy_id    VARCHAR(255) NOT NULL,
    goal_name     VARCHAR(200) NOT NULL,
    success_count INT          NOT NULL DEFAULT 0,
    failure_count INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_goal_signal UNIQUE (agent_id, tenancy_id, goal_name)
);
