CREATE TABLE agent_goal (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descriptor_id  BIGINT       NOT NULL REFERENCES agent_descriptor(internal_id) ON DELETE CASCADE,
    agent_id       VARCHAR(255) NOT NULL,
    tenancy_id     VARCHAR(255) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT         NOT NULL,
    priority       VARCHAR(20)  NOT NULL,
    visibility     VARCHAR(20)  NOT NULL,
    UNIQUE (descriptor_id, name)
);

CREATE TABLE agent_constraint (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descriptor_id  BIGINT       NOT NULL REFERENCES agent_descriptor(internal_id) ON DELETE CASCADE,
    agent_id       VARCHAR(255) NOT NULL,
    tenancy_id     VARCHAR(255) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT         NOT NULL,
    visibility     VARCHAR(20)  NOT NULL,
    severity       VARCHAR(20)  NOT NULL,
    UNIQUE (descriptor_id, name)
);
